export const ROUTES = {
    home: "/",
    aboutUs: "/o-nas",
    pricing: "/cennik",
    gallery: "/galeria",
    contact: "/kontakt",
    offer: "/oferta",
    policy: "/polityka",
    vouchers: "/vouchery",
    massagesOriental: "/masaze-orientalne",
    massagesRelaxtion: "/masaze-relaksacyjne",
    massagesWarming: "/masaze-rozgrzewajace",
    massagesRituals: "/rytualy",
    massagesTreatments: "/masaze-zabiegi",
}